public enum VKCode
{
    Back    =   0x08,
    Enter   =   0x0D,
    Shift   =   0x10,
    Space   =   0x20,
    PageUp  =   0x21,
    PageDown=   0x22,
    Left    =   0x25,
    Up      =   0x26,
    Right   =   0x27,
    Down    =   0x28,
    Del     =   0x21,
    Numbers =   0x30,
    Letters =   0x41,
    Semicolon=  0xBA,
    Plus    =   0xBB,
    Comma   =   0xBC,
    Minus   =   0xBD,
    Period  =   0xBE,
    Slash   =   0xBF,
    Backquote=  0xC0,
    L_Mid_Bracket = 0xDB,
    Backslash=  0xDC,
    R_Mid_Bracket = 0xDD,
    Quote   =   0xDE,
}