//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Keyboard : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 slide
        {
            get
            {
                return SteamVR_Actions.keyboard_slide;
            }
        }
        
        public virtual SteamVR_Action_Boolean touch
        {
            get
            {
                return SteamVR_Actions.keyboard_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean press
        {
            get
            {
                return SteamVR_Actions.keyboard_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean select
        {
            get
            {
                return SteamVR_Actions.keyboard_select;
            }
        }
        
        public virtual SteamVR_Action_Boolean delete
        {
            get
            {
                return SteamVR_Actions.keyboard_delete;
            }
        }
        
        public virtual SteamVR_Action_Boolean fitting
        {
            get
            {
                return SteamVR_Actions.keyboard_fitting;
            }
        }
        
        public virtual SteamVR_Action_Boolean over
        {
            get
            {
                return SteamVR_Actions.keyboard_over;
            }
        }
    }
}
